# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Helpdesk Ticket Partner Response - Auto-generated Mail Header",
    "summary": "Suppress stage updates in response to auto-generated emails",
    "version": "18.0.1.0.0",
    "license": "AGPL-3",
    "category": "Helpdesk",
    "author": "Nitrokey, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/helpdesk",
    "depends": [
        "helpdesk_ticket_partner_response",
        "mail_autogenerated_header",
    ],
    "application": False,
}
