# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo.addons.helpdesk_mgmt.tests.common import TestHelpdeskTicketBase


class TestAutogeneratedHeader(TestHelpdeskTicketBase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.template = cls.env["mail.template"].create(
            {
                "name": "Test Welcome Reply",
                "model_id": cls.env.ref("helpdesk_mgmt.model_helpdesk_ticket").id,
                "subject": "We received your ticket",
                "body_html": "<p>Thank you for contacting us!</p>",
            }
        )
        cls.new_stage.mail_template_id = cls.template

    def _make_ticket(self):
        return self.env["helpdesk.ticket"].create(
            {
                "name": "Test ticket",
                "description": "Test description",
                "team_id": self.team_a.id,
                "stage_id": self.new_stage.id,
                "partner_email": "customer@example.com",
            }
        )

    def test_welcome_email_sent_for_normal_email(self):
        """Stage template is included when no auto-reply context is set."""
        ticket = self._make_ticket()
        result = ticket._track_template({"stage_id": self.new_stage})
        self.assertIn("stage_id", result)

    def test_welcome_email_not_sent_for_autogenerated_email(self):
        """Stage template is suppressed for auto-generated emails."""
        ticket = self._make_ticket()
        result = ticket.with_context(mail_autogenerated_header=True)._track_template(
            {"stage_id": self.new_stage}
        )
        self.assertNotIn("stage_id", result)
