# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import models


class HelpdeskTicket(models.Model):
    _inherit = "helpdesk.ticket"

    def _track_template(self, tracking):
        res = super()._track_template(tracking)
        if self._track_template_skip_autoreply():
            # Suppress the stage welcome email in response to auto-generated
            # emails (e.g. out-of-office replies, delivery notifications).
            res.pop("stage_id", None)
        return res

    def _track_template_skip_autoreply(self):
        """Return True to suppress the stage welcome email for this ticket."""
        return bool(self.env.context.get("mail_autogenerated_header"))
