# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

import email

from odoo.addons.helpdesk_ticket_partner_response.tests.test_partner_response import (
    MAIL_TEMPLATE,
    TestCustomerResponse,
)

AUTOREPLY_MAIL_TEMPLATE = MAIL_TEMPLATE.replace(
    "MIME-Version: 1.0",
    "Auto-Submitted: auto-replied\nMIME-Version: 1.0",
)


class TestAutogeneratedHeader(TestCustomerResponse):
    def _parse_message(self, raw):
        return email.message_from_string(
            raw.format(
                to="helpdesk@example.com",
                subject="Test",
                email_from=self.partner_portal.email,
                msg_id="<test@example.com>",
            )
        )

    def _make_routes(self, ticket):
        return [("helpdesk.ticket", ticket.id, {}, None, None)]

    def test_skip_hook_true_for_autoreply(self):
        """_skip_ticket_stage_update_from_autoreply returns True for auto-reply."""
        ticket = self._create_ticket(self.helpdesk_team1, self.partner_portal)
        msg = self._parse_message(AUTOREPLY_MAIL_TEMPLATE)
        result = self.env["mail.thread"]._skip_ticket_stage_update_from_autoreply(
            msg, {}, self._make_routes(ticket)
        )
        self.assertTrue(result)

    def test_skip_hook_false_for_normal_email(self):
        """_skip_ticket_stage_update_from_autoreply returns False for normal email."""
        ticket = self._create_ticket(self.helpdesk_team1, self.partner_portal)
        msg = self._parse_message(MAIL_TEMPLATE)
        result = self.env["mail.thread"]._skip_ticket_stage_update_from_autoreply(
            msg, {}, self._make_routes(ticket)
        )
        self.assertFalse(result)
