# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Helpdesk Management - Auto-generated Mail Header",
    "summary": "Suppress helpdesk welcome emails in response to auto-generated emails",
    "version": "18.0.1.0.0",
    "license": "AGPL-3",
    "category": "Helpdesk",
    "author": "Nitrokey, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/helpdesk",
    "depends": ["helpdesk_mgmt", "mail_autogenerated_header"],
    "application": False,
}
