[project]
name = "odoo-addons-oca-helpdesk"
version = "19.0.20260805.0"
dependencies = [
    "odoo-addon-helpdesk_mgmt==19.0.*",
    "odoo-addon-helpdesk_mgmt_activity==19.0.*",
    "odoo-addon-helpdesk_mgmt_fieldservice==19.0.*",
    "odoo-addon-helpdesk_mgmt_project==19.0.*",
    "odoo-addon-helpdesk_mgmt_rating==19.0.*",
    "odoo-addon-helpdesk_product==19.0.*",
    "odoo-addon-helpdesk_ticket_close_inactive==19.0.*",
    "odoo-addon-helpdesk_ticket_partner_response==19.0.*",
    "odoo-addon-helpdesk_ticket_related==19.0.*",
    "odoo-addon-helpdesk_type==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
